project:
  type: website
  output-dir: docs

website:
  title: "Movement ecology study design"
  search: false
  back-to-top-navigation: true
  page-navigation: true
  
  repo-url: "https://github.com/ecoisilva/studydesign_ms"
  repo-actions: [edit, issue]
  
  page-footer: 
    left: "Made with [Quarto](https://quarto.org), by Inês Silva. License: [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.en)."
    right: 
      - icon: envelope
        href: mailto:i.simoes-silva@hzdr.de
      - icon: github
        href: https://github.com/ecoisilva
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0000-0003-4850-6193
  
  navbar:
    right:
      - text: movedesign application
        menu:
          - text: Website
            href: "https://ecoisilva.github.io/movedesign/"
          - text: Source code
            href: "https://github.com/ecoisilva/movedesign"
      - text: About
        href: about.qmd
      - text: Tutorial (with Shiny)
        href: tutorial_pop.qmd
      - text: Tutorial (with R)
        href: tutorial_pop_console.qmd
        
      - icon: github
        href: "https://github.com/ecoisilva/studydesign_ms"

format:
  html:
    theme:
      - litera
      - assets/custom.scss
    highlight-style: monokai
    toc: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    citations-hover: true
    footnotes-hover: true
    smooth-scroll: true
     
editor: visual
